### ISSUE TITLE
java.lang.NullPointerException: org.opensaml.xml.signature.SignatureValidator.buildSignature

### ISSUE THREAD

**Issue by KiloKilo7** [lastpass/jira-saml#1]
According to the SAML specification it's not mandatory to have the "SessionOnOrAfter" attribute within the "AuthnStatement" though the plugin code checks for that. Add it by modifying the buildSAMLAssertion method in ResponseBuilder class.

java.lang.NullPointerException
	org.opensaml.xml.signature.SignatureValidator.buildSignature(SignatureValidator.java:92)
	org.opensaml.xml.signature.SignatureValidator.validate(SignatureValidator.java:56)
	com.lastpass.saml.SAMLClient.validate(SAMLClient.java:171)
	com.lastpass.saml.SAMLClient.validateResponse(SAMLClient.java:429)
	com.lastpass.jira.SAMLAuthenticator.getUser(SAMLAuthenticator.java:195)

**Comment by bcopeland** [comment]
Which IdP are you using?

**Comment by KiloKilo7** [comment]
ADFS

Keith

**Comment by KiloKilo7** [comment]
ADFS

**Comment by KiloKilo7** [comment]
also: 
http://mail.wso2.org/mailarchive/dev/2015-February/043538.html

**Comment by KiloKilo7** [comment]
Sorry, I thought this was related to another similar issue I saw regarding "SessionOnOrAfter" . I can see it is different now. For some reason, it is failing when   Signature sig = response.getSignature();
        sigValidator.validate(sig);

**Comment by bcopeland** [comment]
Well, if you can send a copy of an assertion I can take a look at the plugin.  We only really tested against LastPass IdP.  Obviously NPE on validating the assertion is unwanted but I'd like to have some test data to go on to make sure that's the only issue.

**Comment by KiloKilo7** [comment]
Thank you! Could I send it to via a non-public means?

**Comment by bcopeland** [comment]
Yes - you can send to copeland@lastpass.com and you can use the gpg//pgp key for that address if you wish to encrypt it (keyid 6CCE2D2F on the keyserver.)  An expired assertion should be fine for testing though.

**Comment by bcopeland** [comment]
This should be resolved now due to update in saml-sdk-java v0.2.0.  Thanks for the testing and help identifying the issue!
